/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Savannah Summer Design System
        void: "#0C0A09",
        "void-navy": "#1C1917",
        elevated: "#29221D",
        "elevated-hover": "#2A2422",
        "border-dark": "#29221D",
        "border-darker": "#3D3229",
        amber: {
          400: "#FBBF24",
          500: "#F59E0B",
          600: "#D97706",
          glow: "rgba(245, 158, 11, 0.4)",
        },
        sunset: "#F97316",
        sage: "#84CC16",
        cream: "#FAF5EF",
        "cream-secondary": "#C4B5A0",
        "cream-muted": "#7A6E5F",
        espresso: "#0C0A09",
        txt: {
          primary: "#FAF5EF",
          secondary: "#C4B5A0",
          muted: "#7A6E5F",
        },
        savannah: {
          void: "#0C0A09",
          card: "#1C1917",
          input: "#231F1E",
          border: "#29221D",
          "border-light": "#3D3229",
          amber: "#F59E0B",
          "amber-dark": "#D97706",
          "amber-light": "#FBBF24",
          "amber-glow": "rgba(245, 158, 11, 0.35)",
          sunset: "#F97316",
          cream: "#FAF5EF",
          "cream-secondary": "#C4B5A0",
          "cream-muted": "#7A6E5F",
          sage: "#84CC16",
        },
      },
      fontFamily: {
        sans: ['Space Grotesk', 'system-ui', 'sans-serif'],
        inter: ['Space Grotesk', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        glow: "0 0 20px rgba(245, 158, 11, 0.4)",
        "glow-lg": "0 0 40px rgba(245, 158, 11, 0.5)",
        "glow-sm": "0 0 10px rgba(245, 158, 11, 0.3)",
        card: "0 1px 3px rgba(0, 0, 0, 0.3), 0 1px 2px rgba(0, 0, 0, 0.2)",
        "card-hover": "0 8px 24px rgba(0, 0, 0, 0.4), 0 0 20px rgba(245, 158, 11, 0.1)",
        "amber-glow": "0 0 20px rgba(245, 158, 11, 0.35)",
        "amber-glow-lg": "0 0 40px rgba(245, 158, 11, 0.5)",
        "amber-glow-sm": "0 0 10px rgba(245, 158, 11, 0.3)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "fade-slide-up": {
          from: { opacity: "0", transform: "translateY(24px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-slide-left": {
          from: { opacity: "0", transform: "translateX(-24px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "scale-fade": {
          from: { opacity: "0", transform: "scale(0.9)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% center" },
          "100%": { backgroundPosition: "200% center" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 8px rgba(245,158,11,0.2)" },
          "50%": { boxShadow: "0 0 24px rgba(245,158,11,0.5)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0) translateX(0)" },
          "25%": { transform: "translateY(-20px) translateX(10px)" },
          "50%": { transform: "translateY(-10px) translateX(-15px)" },
          "75%": { transform: "translateY(-30px) translateX(5px)" },
        },
        "ring-pulse": {
          "0%": { transform: "scale(1)", opacity: "0.6" },
          "100%": { transform: "scale(2.5)", opacity: "0" },
        },
        blink: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
        "slow-rotate": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        "stagger-fade-in": {
          from: { opacity: "0", transform: "translateY(20px) scale(0.96)" },
          to: { opacity: "1", transform: "translateY(0) scale(1)" },
        },
        "neural-pulse": {
          "0%": { strokeDashoffset: "100", opacity: "0.3" },
          "50%": { opacity: "1" },
          "100%": { strokeDashoffset: "0", opacity: "0.3" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "fade-slide-up": "fade-slide-up 0.5s ease-out forwards",
        "fade-slide-left": "fade-slide-left 0.5s ease-out forwards",
        "scale-fade": "scale-fade 0.4s ease-out forwards",
        shimmer: "shimmer 2s linear infinite",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        float: "float 8s ease-in-out infinite",
        "ring-pulse": "ring-pulse 1.5s ease-out infinite",
        blink: "blink 1s steps(1) infinite",
        "slow-rotate": "slow-rotate 20s linear infinite",
        "stagger-fade-in": "stagger-fade-in 0.5s ease-out forwards",
        "neural-pulse": "neural-pulse 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
