import { callOpenRouter, MODELS } from "./openrouter";

const openaiKey = process.env.OPENAI_API_KEY;
const groqKey = process.env.GROQ_API_KEY;
const openrouterKey = process.env.OPENROUTER_API_KEY;

function getClient() {
  // Single-key priority: OpenRouter gives access to all routed models
  if (openrouterKey) return { type: "openrouter", key: openrouterKey };
  if (groqKey) return { type: "groq", key: groqKey };
  if (openaiKey) return { type: "openai", key: openaiKey };
  return null;
}

/** Shared OpenRouter chat call for agent/caption/chat flows */
async function callViaOpenRouter(
  systemPrompt: string,
  userPrompt: string,
  model: string,
  temperature: number,
  maxTokens: number
): Promise<string | null> {
  try {
    return await callOpenRouter(
      [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      { model, temperature, maxTokens }
    );
  } catch (err) {
    console.error("[AI] OpenRouter error:", (err as Error).message);
    return null;
  }
}

/**
 * Build a system prompt that respects the agent's identity.
 * For Vision (Creative Director), we use the raw role directly — no generic wrapper —
 * because the persona is carefully crafted to be Jobs + Godin + guru.
 * For other agents, we wrap with a light generic intro.
 */
function buildSystemPrompt(agentName: string, agentRole: string, brandVoice?: { tone: string; description: string } | null): string {
  const isVision = agentName === "Vision";

  let prompt: string;
  if (isVision) {
    // Vision gets the raw, unadulterated persona. No generic wrapper.
    prompt = agentRole;
  } else {
    prompt = `You are ${agentName}, an expert AI marketing agent. ${agentRole}. Generate high-quality, actionable marketing content. Be specific, creative, and data-driven.`;
  }

  if (brandVoice) {
    prompt += `\n\nWrite in this brand voice: ${brandVoice.tone}. ${brandVoice.description}`;
  }

  return prompt;
}

/**
 * Build a chat system prompt. Same logic — Vision gets the raw persona.
 */
function buildChatSystemPrompt(agentName: string, agentRole: string, brandVoice?: { tone: string; description: string } | null): string {
  const isVision = agentName === "Vision";

  let prompt: string;
  if (isVision) {
    prompt = `${agentRole}\n\nYou are currently in a real-time chat with a user in a marketing agency platform. Respond conversationally — concise, punchy, and with conviction. Ask the hard questions. Push back on mediocrity. Reveal, don't explain.`;
  } else {
    prompt = `You are ${agentName}, an expert AI marketing agent. ${agentRole}. You are chatting with a user in a marketing agency platform. Respond conversationally, helpfully, and concisely. Be friendly and professional.`;
  }

  if (brandVoice) {
    prompt += `\n\nWrite in this brand voice: ${brandVoice.tone}. ${brandVoice.description}`;
  }

  return prompt;
}

function fallbackAgentOutput(agentName: string, campaignObjective: string): string {
  return `# ${agentName} — Campaign Strategy

**Objective:** ${campaignObjective}

> ⚠️ AI generation is using fallback mode. Add OPENROUTER_API_KEY to Railway for real AI-generated content.

## Recommendations

1. Define clear KPIs aligned with your objective
2. Segment your audience for targeted messaging
3. Test multiple creative variants
4. Monitor performance daily and optimize
5. Document learnings in the Memory Bank

---
*Generated by Omega Swarm*`;
}

export async function generateWithAgent(
  agentName: string,
  agentRole: string,
  campaignObjective: string,
  budget: string,
  timeline: string,
  brandVoice?: { tone: string; description: string } | null,
  memoryContext?: string
): Promise<string> {
  const client = getClient();
  if (!client) {
    console.warn("[AI] No API key set — using fallback agent output. Add OPENROUTER_API_KEY to Railway.");
    return fallbackAgentOutput(agentName, campaignObjective);
  }

  const systemPrompt = buildSystemPrompt(agentName, agentRole, brandVoice) + (memoryContext ?? "");

  const userPrompt = `Campaign Brief:
- Objective: ${campaignObjective}
- Budget: ${budget}
- Timeline: ${timeline}

Generate your deliverables. Be thorough and specific.`;

  try {
    if (client.type === "openrouter") {
      const out = await callViaOpenRouter(systemPrompt, userPrompt, MODELS.PLANNER, 0.8, 2000);
      return out || fallbackAgentOutput(agentName, campaignObjective);
    }
    if (client.type === "groq") {
      const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${client.key}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "openai/gpt-oss-120b",
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userPrompt },
          ],
          temperature: 0.8,
          max_tokens: 2000,
        }),
      });
      if (!res.ok) {
        const err = await res.text();
        console.error("[AI] Groq error:", res.status, err);
        return fallbackAgentOutput(agentName, campaignObjective);
      }
      const data = await res.json();
      return data.choices?.[0]?.message?.content || fallbackAgentOutput(agentName, campaignObjective);
    }

    // OpenAI fallback
    const { default: OpenAI } = await import("openai");
    const openai = new OpenAI({ apiKey: client.key });
    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      temperature: 0.8,
      max_tokens: 2000,
    });
    return response.choices[0]?.message?.content || fallbackAgentOutput(agentName, campaignObjective);
  } catch (err) {
    console.error("[AI] Agent generation failed:", (err as Error).message);
    return fallbackAgentOutput(agentName, campaignObjective);
  }
}

export async function generateImage(prompt: string, provider?: "pollinations" | "openai"): Promise<string> {
  // Premium: OpenAI DALL-E 3 — fast (~5s), high quality, costs ~$0.04/image
  if (provider === "openai" && openaiKey) {
    const { default: OpenAI } = await import("openai");
    const openai = new OpenAI({ apiKey: openaiKey });
    const response = await openai.images.generate({
      model: "dall-e-3",
      prompt,
      size: "1024x1024",
      quality: "standard",
      n: 1,
    });
    return response.data[0]?.url || "";
  }

  // Free fallback: Pollinations.ai — slow (~15-30s), no API key
  // Use a small random seed (0-999999) — Pollinations chokes on Date.now() seeds > 1 billion
  const encoded = encodeURIComponent(prompt);
  const seed = Math.floor(Math.random() * 1000000);
  return `https://image.pollinations.ai/prompt/${encoded}?width=1024&height=1024&nologo=true&seed=${seed}`;
}

/**
 * Groq model ID used below: "openai/gpt-oss-120b".
 * This IS a Groq-native model ID — Groq's hosted OpenAI open-weight model
 * (console.groq.com → docs → models). The openai/ prefix is part of Groq's own
 * naming; it is NOT an OpenRouter-format ID. Verified against Groq's live model
 * catalog 2026-08. Do not "correct" it to llama-* — those are deprecated.
 */
function fallbackCaption(topic: string, brandVoice?: string): string {
  const voice = brandVoice ? `Written in a ${brandVoice} tone. ` : "";
  return `${voice}✨ ${topic} ✨\n\nThis is AI-generated content from Omega Swarm. Add OPENROUTER_API_KEY to Railway for real AI-generated captions.\n\n#OmegaSwarm #AI #Marketing #ContentCreation`;
}

export async function generateCaption(topic: string, brandVoice?: string, memoryContext?: string): Promise<string> {
  const client = getClient();
  if (!client) {
    console.warn("[AI] No API key set — using fallback caption. Add OPENROUTER_API_KEY to Railway.");
    return fallbackCaption(topic, brandVoice);
  }

  const systemPrompt = `You are a social media expert. Write an engaging Instagram caption. ${brandVoice || ""} Include relevant hashtags. Keep it under 2,200 characters.${memoryContext ?? ""}`;

  try {
    if (client.type === "openrouter") {
      const out = await callViaOpenRouter(
        systemPrompt,
        `Write an Instagram caption about: ${topic}`,
        MODELS.COPYWRITER,
        0.9,
        1500
      );
      return out || fallbackCaption(topic, brandVoice);
    }
    if (client.type === "groq") {
      const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${client.key}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "openai/gpt-oss-120b",
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: `Write an Instagram caption about: ${topic}` },
          ],
          temperature: 0.9,
          max_tokens: 1500,
        }),
      });
      if (!res.ok) {
        const err = await res.text();
        console.error("[AI] Groq error:", res.status, err);
        return fallbackCaption(topic, brandVoice);
      }
      const data = await res.json();
      return data.choices?.[0]?.message?.content || fallbackCaption(topic, brandVoice);
    }

    // OpenAI fallback
    const { default: OpenAI } = await import("openai");
    const openai = new OpenAI({ apiKey: client.key });
    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: `Write an Instagram caption about: ${topic}` },
      ],
      temperature: 0.9,
      max_tokens: 1500,
    });
    return response.choices[0]?.message?.content || fallbackCaption(topic, brandVoice);
  } catch (err) {
    console.error("[AI] Caption generation failed:", (err as Error).message);
    return fallbackCaption(topic, brandVoice);
  }
}

function fallbackChat(agentName: string, userMessage: string): string {
  return `[${agentName}] I hear you on "${userMessage.slice(0, 50)}..."\n\n> ⚠️ I'm running in fallback mode. Add OPENROUTER_API_KEY to Railway for real AI conversations.`;
}

export async function chatWithAgent(
  agentName: string,
  agentRole: string,
  userMessage: string,
  brandVoice?: { tone: string; description: string } | null,
  memoryContext?: string
): Promise<string> {
  const client = getClient();
  if (!client) {
    console.warn("[AI] No API key set — using fallback chat. Add OPENROUTER_API_KEY to Railway.");
    return fallbackChat(agentName, userMessage);
  }

  const systemPrompt = buildChatSystemPrompt(agentName, agentRole, brandVoice) + (memoryContext ?? "");
  const userPrompt = userMessage;

  try {
    if (client.type === "openrouter") {
      const out = await callViaOpenRouter(systemPrompt, userPrompt, MODELS.COPYWRITER, 0.8, 1500);
      return out || fallbackChat(agentName, userMessage);
    }
    if (client.type === "groq") {
      const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${client.key}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "openai/gpt-oss-120b",
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userPrompt },
          ],
          temperature: 0.8,
          max_tokens: 1500,
        }),
      });
      if (!res.ok) {
        const err = await res.text();
        console.error("[AI] Groq error:", res.status, err);
        return fallbackChat(agentName, userMessage);
      }
      const data = await res.json();
      return data.choices?.[0]?.message?.content || fallbackChat(agentName, userMessage);
    }

    // OpenAI fallback
    const { default: OpenAI } = await import("openai");
    const openai = new OpenAI({ apiKey: client.key });
    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      temperature: 0.8,
      max_tokens: 1500,
    });
    return response.choices[0]?.message?.content || fallbackChat(agentName, userMessage);
  } catch (err) {
    console.error("[AI] Chat failed:", (err as Error).message);
    return fallbackChat(agentName, userMessage);
  }
}
